### ISSUE TITLE
Question regarding resolution

### ISSUE THREAD

**Issue by ashleigh-yeoman** [smacker/esbuild-plugin-ts-references#5]
I'm in a position where the monorepo I'm working in may contain several reference levels in the near future.

For example
```mermaid
graph LR;
    MainApp-->RendererService;
    RendererService-->Common;
    MainApp-->Common;
```
which could end up being a problem if references are resolved only 1 level deep. Since the entry-point would be `MainApp`, importing `RendererService` may result in being unable to resolve `Common` for `RendererService`.

I'm only using esbuild directly for a serverless package, while I use Vite for building the rest of the monorepo. I mention this, because I use [vite-tsconfig-paths](https://github.com/aleclarson/vite-tsconfig-paths) in my Vite config.

`vite-tsconfig-paths` uses `tsconfck` under the hood, which resolves tsconfig files recursively. So there shouldn't be any issues on the Vite side of things, but I need to make sure the same can be said for the esbuild side of things.

So my question is: does `esbuild-plugin-ts-references` support recursive resolution of project references? If not, is there any possibility of adapting this plugin to use a similar method to `vite-tsconfig-paths`?

**Comment by smacker** [comment]
Modules are resolved with their absolute path. Essentially the plugin builds a map:
```
{
  '@my-monorepo/renderer': '/path/to/monorepo/src/renderer',
  '@my-monorepo/common':  '/path/to/monorepo/src/common',
}
```

So no matter where you import `@my-monorepo/common` from, it will always be resolved to `/path/to/monorepo/src/common`.
